[build]
target = "index.html"
dist = "dist"

[watch]
watch = ["src", "index.html", "tailwind.css"]

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npx tailwindcss -i ./tailwind.css -o ./public/output.css --minify"]
